services:
  db4:
    image: postgres:15-alpine
    container_name: db4
    restart: unless-stopped
    ports:
      - "45432:5432"
    environment:
      - POSTGRES_USER=user4
      - POSTGRES_PASSWORD=password4
      - POSTGRES_DB=db4
    volumes:
      - ./db4:/var/lib/postgresql/data
    networks:
      - shared-network
  db3:
    image: postgres:15-alpine
    container_name: db3
    restart: unless-stopped
    ports:
      - "35432:5432"
    environment:
      - POSTGRES_USER=user3
      - POSTGRES_PASSWORD=password3
      - POSTGRES_DB=db3
    volumes:
      - ./db3:/var/lib/postgresql/data
    networks:
      - shared-network
volumes:
  postgres_data: null
networks:
  shared-network: null
